### ISSUE TITLE
テンプレートエンジンを使うべき

### ISSUE THREAD

**Issue by kmyk** [kosakkun/Endless-Marathon#1]
CGI を使う場合でも backend / frontend に分ける場合でも、HTMLを.pyに直書きは最善ではないです。
テンプレートの部分的な使い回しが楽、変数の埋め込みがしやすい、うっかり `\` のエスケープ忘れで困らない、HTML injectionに強い、エディタがsyntax highlightをしてくれる、などの利点があります。

Jinja2 ってのが有名で無難 http://jinja.pocoo.org/
少しマイナーな mako ってのもあって人によってはこちらの方が好きかも https://www.makotemplates.org/

**Comment by kosakkun** [comment]
Jinja2にしました．

**Comment by kmyk** [comment]
:+1:
