### ISSUE TITLE
問題の追加や管理ができるようにしてほしい

### ISSUE THREAD

**Issue by kmyk** [kosakkun/Endless-Marathon#14]
そういう管理画面を作ってもよいですし、ドキュメントとしてまとめてくれてもよいです

**Comment by kosakkun** [comment]
管理画面を作ろうと思います．今の状態だとテスタ（.jarファイル）はDBに入ってないんですが，これもDBで管理出来ますか？もしくはどっかに（問題の管理画面で一緒）にアップロードできるようにして，問題のIDとかで参照するのが良さそうですか？

**Comment by kmyk** [comment]
はい、.jar もDBで管理できます。.jar を管理画面からアップロードできるようにするのは理想ですが、必要な実装量を考えると、その他の方法で誤魔化すことも検討した方がいいと思います。

**Comment by kosakkun** [comment]
現状はTSPのテスタが問答無用で動くようになっているので，とりあえず管理画面使えるようになるまで下のやつで問題と言語を追加してください...

```
INSERT INTO problems (
    id,  name, statement, created_at 
) VALUES (
   3, 'tsp', 'nyanchu', '2019-01-01 00:00:00'
);

INSERT INTO languages (
    id, name, how_to_compile, how_to_execute, created_at
) VALUES (
    3, 'cpp', 'nyanchu', 'nyanchu', '2019-01-01 00:00:00'
);
```

**Comment by kmyk** [comment]
了解です。
だとすると現状は `db.sql` にこれを追記しておくのがよさそうですね。

**Comment by kosakkun** [comment]
承知しました．マージしたら追加します．

**Comment by kosakkun** [comment]
DBの管理ページを作りました．
