### ISSUE TITLE
git submodule というのがある

### ISSUE THREAD

**Issue by kmyk** [kosakkun/Endless-Marathon#3]
[codemirror/](https://github.com/kosakkun/Endless-Marathon/tree/4795c2f6efb0128e01f37b59c9399bc4da0f5197/codemirror) と [spark/](https://github.com/kosakkun/Endless-Marathon/tree/4795c2f6efb0128e01f37b59c9399bc4da0f5197/spark) は生で突っ込むのではなくて、この機能を使って参照してあげると綺麗です。
利点としては、行儀が悪くないのでぱっと見の印象が良い、ライセンスの問題のこわさが軽減される、version情報が明確になる、などです。

**Comment by kosakkun** [comment]
submoduleに変更しました．

**Comment by kmyk** [comment]
:+1:
