### ISSUE TITLE
CGI を脱却して flask を使おう

### ISSUE THREAD

**Issue by kmyk** [kosakkun/Endless-Marathon#4]
Flask http://flask.pocoo.org/
イメージはIsuconの予選の初期実装を見ると分かりやすそう https://github.com/isucon/isucon2/blob/master/webapp/python/app.py

CGIはHTTPのprotocolそのものについての理解を助けてくれるので正解ではあるけど、そろそろ便利なやつを持ってきてもよさそう
(そもそも `http.server` を紹介したのもCGIでなくてもうちょっと高級な用法を想定していたが、伝わってなかったのは申し訳ない)

**Comment by kosakkun** [comment]
flask使います．

**Comment by kmyk** [comment]
`cgi-bin/` は消し忘れ？

**Comment by kosakkun** [comment]
submitのページの処理をまだ移動出来ていないので前のファイルを残しています．DB の Schema 定義が出来たら消す予定です．

**Comment by kmyk** [comment]
なるほど
