### ISSUE TITLE
Issueへの参照を貼ろう

### ISSUE THREAD

**Issue by kmyk** [kosakkun/Endless-Marathon#6]
例えば #5 の https://github.com/kosakkun/Endless-Marathon/issues/5#issuecomment-467490311 とかも 04aa8bebf2f67dcc03ad4758f8d97d7e3b43bf0d って書くと、書くのも読むのも楽でしあわせになれます。commit message 中に `#5` とか書いてもいい感じに参照が貼られるのでぜひ

**Comment by kosakkun** [comment]
なるほど．

**Comment by kosakkun** [comment]
貼り方分かった．貼ってみた．

**Comment by kmyk** [comment]
:+1:
