### ISSUE TITLE
secret_key を公開してはいけない

### ISSUE THREAD

**Issue by kmyk** [kosakkun/Endless-Marathon#9]
`secret_key` は secret な key なので

https://github.com/kosakkun/Endless-Marathon/blob/5d9da791ae9a967ef2a3459cbf9db9b79cff3c1f/run.py#L19

**Comment by kosakkun** [comment]
丸見えですね...

**Comment by kmyk** [comment]
session情報の暗号化に使われるという話なので、これが漏れるとログインを突破されそう

**Comment by kosakkun** [comment]
そういえば，このsecret_keyとかMySQLのパスワードだったりはどんな感じで管理したら外から見えなくなりますか？

**Comment by kmyk** [comment]
手元にgit管理外の `env.sh` のようなファイルを作って環境変数を経由して渡すことが多いです。あるいは `env.json` などに書いて直接ファイルとして読んでもよいです。

**Comment by kosakkun** [comment]
サーバにだけ置いておくファイル作って（権限かなんかで見れなくして）って感じなんですね．

**Comment by kmyk** [comment]
はい

**Comment by kosakkun** [comment]
こんな感じでいいですか？
58d53568285f11e1ffa2445447ad01abc5373af2
```
-rw------- 1 kosakkun kosakkun    51 May 12 05:16 secret_key.json
```

**Comment by kosakkun** [comment]
こんな感じでいいですか？
58d53568285f11e1ffa2445447ad01abc5373af2
```
-rw------- 1 *** ***    51 May 12 05:16 secret_key.json
```

**Comment by kmyk** [comment]
方向は合ってる。細部は2点気になったので https://github.com/kosakkun/Endless-Marathon/commit/58d53568285f11e1ffa2445447ad01abc5373af2 にコメントを書きました

**Comment by kmyk** [comment]
https://github.com/kosakkun/Endless-Marathon/commit/3ac1dc054231201527208d7ec0c06fc35945fe85 で解決できてるね
